apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment-app
          image: robotshop/rs-payment:latest
          ports:
            - containerPort: 8080
          env:
            - name: CART_HOST
              valueFrom:
                configMapKeyRef:
                  name: robot-shop-config
                  key: CART_HOST
            - name: USER_HOST
              valueFrom:
                configMapKeyRef:
                  name: robot-shop-config
                  key: USER_HOST
            - name: AMQP_HOST
              valueFrom:
                configMapKeyRef:
                  name: robot-shop-config
                  key: AMQP_HOST
            - name: PAYMENT_GATEWAY
              valueFrom:
                configMapKeyRef:
                  name: robot-shop-config
                  key: PAYMENT_GATEWAY
            - name: PAYMENT_DELAY_MS
              valueFrom:
                configMapKeyRef:
                  name: robot-shop-config
                  key: PAYMENT_DELAY_MS
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
